version: "3.9"
services:
  backend:
    build:
      context: ./WebAPI
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
